### Get currently signed in user
GET http://localhost:3000/auth/whoami


### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "test@test.com",
  "password": "12345"
}

### Signin
POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "test@test.com",
  "password": "12345"
}

### Signout
POST http://localhost:3000/auth/signout

### Get a user by id
GET http://localhost:3000/auth/4

### Find all users with given email
GET http://localhost:3000/auth?email=asd@glkjdf.com


### Remove a user by id
DELETE http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/2
content-type: application/json

{
  "email": "france@ferdinand.com"
}